POST http://localhost:3003/api/quotes 
content-type: application/json 
Authorization: bearer asd

{
  "quo": "No matter where you go, everyone's connected.",
  "character": "Lain Iwakura",
  "anime": "Serial Experiments Lain"
}